/*
 * Decompiled with CFR 0.152.
 */
package net;

import cc.novoline.invoke.BootstrapInvoker;
import cc.novoline.invoke.ListInvoker;
import cc.novoline.string.StringPool2;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemEnchantedBook;
import java.util.ArrayList;
import java.util.List;

public class Items {
    public static Item record_chirp;
    public static Item sugar;
    public static ItemArmor golden_boots;
    public static Item hopper_minecart;
    public static Item firework_charge;
    public static Item writable_book;
    public static ItemArmor iron_leggings;
    public static Item wooden_hoe;
    public static Item wheat_seeds;
    public static ItemArmor chainmail_helmet;
    public static Item golden_horse_armor;
    public static Item written_book;
    public static Item record_mellohi;
    public static ItemArmor iron_chestplate;
    public static Item water_bucket;
    public static Item golden_sword;
    public static Item slime_ball;
    public static Item skull;
    public static Item record_strad;
    public static Item diamond_pickaxe;
    public static Item prismarine_crystals;
    public static ItemArmor golden_helmet;
    public static Item record_wait;
    public static Item pumpkin_seeds;
    public static Item golden_apple;
    public static Item reeds;
    public static Item stone_pickaxe;
    public static ItemArmor diamond_boots;
    public static Item fermented_spider_eye;
    public static Item stone_hoe;
    public static Item gold_ingot;
    public static Item apple;
    public static Item cooked_mutton;
    public static Item paper;
    public static ItemShears shears;
    public static Item ender_eye;
    public static Item cooked_rabbit;
    public static Item birch_door;
    public static Item leather;
    public static Item potato;
    public static ItemEmptyMap map;
    public static Item spruce_door;
    public static ItemArmor golden_leggings;
    public static Item painting;
    public static ItemArmor diamond_chestplate;
    public static ItemArmor golden_chestplate;
    public static Item golden_carrot;
    public static Item nether_wart;
    public static Item saddle;
    public static Item cooked_fish;
    public static ItemFishingRod fishing_rod;
    public static Item cooked_beef;
    public static Item feather;
    public static Item rotten_flesh;
    public static ItemArmor leather_helmet;
    public static Item dye;
    public static Item lead;
    public static Item experience_bottle;
    public static Item arrow;
    public static Item golden_shovel;
    public static Item string;
    public static Item name_tag;
    public static Item ender_pearl;
    public static Item spider_eye;
    public static Item book;
    public static Item wooden_axe;
    public static Item comparator;
    public static Item diamond_horse_armor;
    public static Item golden_axe;
    public static Item diamond_axe;
    public static Item carrot;
    public static Item fish;
    public static Item fireworks;
    public static Item melon_seeds;
    public static Item coal;
    public static Item dark_oak_door;
    public static Item clock;
    public static Item glowstone_dust;
    public static Item iron_ingot;
    public static Item redstone;
    public static Item wheat;
    public static Item speckled_melon;
    public static Item acacia_door;
    public static Item golden_hoe;
    public static Item rabbit_foot;
    public static ItemBow bow;
    public static Item item_frame;
    public static Item minecart;
    public static Item egg;
    public static Item poisonous_potato;
    public static Item cooked_chicken;
    public static Item golden_pickaxe;
    public static Item blaze_rod;
    public static Item rabbit_stew;
    public static Item chicken;
    public static Item record_stal;
    public static ItemArmor iron_helmet;
    public static Item chest_minecart;
    public static Item rabbit_hide;
    public static ItemEnchantedBook enchanted_book;
    public static Item milk_bucket;
    public static Item jungle_door;
    public static Item stone_axe;
    public static Item beef;
    public static Item pumpkin_pie;
    public static Item netherbrick;
    public static ItemArmor chainmail_boots;
    public static List<Item> b_;
    public static Item glass_bottle;
    public static Item record_ward;
    public static Item wooden_pickaxe;
    public static Item boat;
    public static Item record_cat;
    public static Item flower_pot;
    public static Item snowball;
    public static Item compass;
    public static Item carrot_on_a_stick;
    public static Item command_block_minecart;
    public static ItemArmor leather_chestplate;
    public static Item cookie;
    public static Item blaze_powder;
    public static Item baked_potato;
    public static Item cauldron;
    public static Item record_mall;
    public static Item cake;
    public static Item wooden_sword;
    public static Item porkchop;
    public static Item iron_door;
    public static ItemArmor iron_boots;
    public static Item iron_shovel;
    public static Item iron_hoe;
    public static Item magma_cream;
    public static Item nether_star;
    public static ItemArmor chainmail_chestplate;
    public static Item melon;
    public static Item gold_nugget;
    public static Item brick;
    public static Item flint;
    public static Item prismarine_shard;
    public static Item iron_horse_armor;
    public static Item flint_and_steel;
    public static Item iron_axe;
    public static Item bed;
    public static Item wooden_shovel;
    public static Item spawn_egg;
    public static ItemMap filled_map;
    public static Item clay_ball;
    public static Item emerald;
    public static Item quartz;
    public static Item diamond_shovel;
    public static Item stone_sword;
    public static Item bowl;
    public static ItemArmor chainmail_leggings;
    public static Item iron_pickaxe;
    public static Item bucket;
    public static ItemArmor leather_boots;
    public static Item diamond_sword;
    public static Item stick;
    public static Item fire_charge;
    public static ItemArmor diamond_leggings;
    public static Item iron_sword;
    public static Item repeater;
    public static Item banner;
    public static Item rabbit;
    public static ItemPotion potionitem;
    public static Item cooked_porkchop;
    public static Item brewing_stand;
    public static Item record_13;
    public static Item mushroom_stew;
    public static Item stone_shovel;
    public static Item bread;
    public static Item mutton;
    public static Item record_11;
    public static ItemArmorStand armor_stand;
    public static Item oak_door;
    public static ItemArmor diamond_helmet;
    public static Item diamond;
    public static Item ghast_tear;
    public static Item diamond_hoe;
    public static Item tnt_minecart;
    public static Item record_blocks;
    public static Item bone;
    public static ItemArmor leather_leggings;
    public static Item lava_bucket;
    public static Item record_far;
    public static Item sign;
    public static Item gunpowder;
    public static Item furnace_minecart;

    private static RuntimeException a(RuntimeException runtimeException) {
        return runtimeException;
    }

    private static Item getRegisteredItem(String string) {
        Item item = (Item)aLP.b(Item.k, new ResourceLocation(string));
        ListInvoker.add(b_, item);
        return item;
    }

    public static Item a() {
        return (Item)ListInvoker.get(b_, anf_2.a(anf_2.c(), 0, ListInvoker.size(b_)));
    }

    static {
        b_ = new ArrayList<Item>();
        if (!BootstrapInvoker.b()) {
            throw new RuntimeException(StringPool2.aK);
        }
        iron_shovel = Items.getRegisteredItem(StringPool2.L);
        iron_pickaxe = Items.getRegisteredItem(StringPool2.a);
        iron_axe = Items.getRegisteredItem(StringPool2.A);
        flint_and_steel = Items.getRegisteredItem(StringPool2.aE);
        apple = Items.getRegisteredItem(StringPool2.bE);
        bow = (ItemBow)Items.getRegisteredItem(StringPool2.ap);
        arrow = Items.getRegisteredItem(StringPool2.b3);
        coal = Items.getRegisteredItem(StringPool2.s);
        diamond = Items.getRegisteredItem(StringPool2.bB);
        iron_ingot = Items.getRegisteredItem(StringPool2.O);
        gold_ingot = Items.getRegisteredItem(StringPool2.aR);
        iron_sword = Items.getRegisteredItem(StringPool2.az);
        wooden_sword = Items.getRegisteredItem(StringPool2.cg);
        wooden_shovel = Items.getRegisteredItem(StringPool2.W);
        wooden_pickaxe = Items.getRegisteredItem(StringPool2.bi);
        wooden_axe = Items.getRegisteredItem(StringPool2.bT);
        stone_sword = Items.getRegisteredItem(StringPool2.P);
        stone_shovel = Items.getRegisteredItem(StringPool2.v);
        stone_pickaxe = Items.getRegisteredItem(StringPool2.d);
        stone_axe = Items.getRegisteredItem(StringPool2.bs);
        diamond_sword = Items.getRegisteredItem(StringPool2.aN);
        diamond_shovel = Items.getRegisteredItem(StringPool2.bN);
        diamond_pickaxe = Items.getRegisteredItem(StringPool2.V);
        diamond_axe = Items.getRegisteredItem(StringPool2.b7);
        stick = Items.getRegisteredItem(StringPool2.aY);
        bowl = Items.getRegisteredItem(StringPool2.aT);
        mushroom_stew = Items.getRegisteredItem(StringPool2.a6);
        golden_sword = Items.getRegisteredItem(StringPool2.aV);
        golden_shovel = Items.getRegisteredItem(StringPool2.an);
        golden_pickaxe = Items.getRegisteredItem(StringPool2.aP);
        golden_axe = Items.getRegisteredItem(StringPool2.ba);
        string = Items.getRegisteredItem(StringPool2.C);
        feather = Items.getRegisteredItem(StringPool2.ae);
        gunpowder = Items.getRegisteredItem(StringPool2.bV);
        wooden_hoe = Items.getRegisteredItem(StringPool2.bm);
        stone_hoe = Items.getRegisteredItem(StringPool2.a2);
        iron_hoe = Items.getRegisteredItem(StringPool2.bL);
        diamond_hoe = Items.getRegisteredItem(StringPool2.K);
        golden_hoe = Items.getRegisteredItem(StringPool2.bA);
        wheat_seeds = Items.getRegisteredItem(StringPool2.cf);
        wheat = Items.getRegisteredItem(StringPool2.aJ);
        bread = Items.getRegisteredItem(StringPool2.bz);
        leather_helmet = (ItemArmor)Items.getRegisteredItem(StringPool2.aa);
        leather_chestplate = (ItemArmor)Items.getRegisteredItem(StringPool2.aq);
        leather_leggings = (ItemArmor)Items.getRegisteredItem(StringPool2.b0);
        leather_boots = (ItemArmor)Items.getRegisteredItem(StringPool2.bh);
        chainmail_helmet = (ItemArmor)Items.getRegisteredItem(StringPool2.au);
        chainmail_chestplate = (ItemArmor)Items.getRegisteredItem(StringPool2.bG);
        chainmail_leggings = (ItemArmor)Items.getRegisteredItem(StringPool2.h);
        chainmail_boots = (ItemArmor)Items.getRegisteredItem(StringPool2.aF);
        iron_helmet = (ItemArmor)Items.getRegisteredItem(StringPool2.bM);
        iron_chestplate = (ItemArmor)Items.getRegisteredItem(StringPool2.bp);
        iron_leggings = (ItemArmor)Items.getRegisteredItem(StringPool2.bJ);
        iron_boots = (ItemArmor)Items.getRegisteredItem(StringPool2.i);
        diamond_helmet = (ItemArmor)Items.getRegisteredItem(StringPool2.w);
        diamond_chestplate = (ItemArmor)Items.getRegisteredItem(StringPool2.g);
        diamond_leggings = (ItemArmor)Items.getRegisteredItem(StringPool2.aC);
        diamond_boots = (ItemArmor)Items.getRegisteredItem(StringPool2.bF);
        golden_helmet = (ItemArmor)Items.getRegisteredItem(StringPool2.cc);
        golden_chestplate = (ItemArmor)Items.getRegisteredItem(StringPool2.a5);
        golden_leggings = (ItemArmor)Items.getRegisteredItem(StringPool2.aD);
        golden_boots = (ItemArmor)Items.getRegisteredItem(StringPool2.br);
        flint = Items.getRegisteredItem(StringPool2.G);
        porkchop = Items.getRegisteredItem(StringPool2.bq);
        cooked_porkchop = Items.getRegisteredItem(StringPool2.ca);
        painting = Items.getRegisteredItem(StringPool2.o);
        golden_apple = Items.getRegisteredItem(StringPool2.T);
        sign = Items.getRegisteredItem(StringPool2.a8);
        oak_door = Items.getRegisteredItem(StringPool2.b6);
        spruce_door = Items.getRegisteredItem(StringPool2.ad);
        birch_door = Items.getRegisteredItem(StringPool2.l);
        jungle_door = Items.getRegisteredItem(StringPool2.by);
        acacia_door = Items.getRegisteredItem(StringPool2.ab);
        dark_oak_door = Items.getRegisteredItem(StringPool2.Y);
        bucket = Items.getRegisteredItem(StringPool2.J);
        water_bucket = Items.getRegisteredItem(StringPool2.t);
        lava_bucket = Items.getRegisteredItem(StringPool2.ay);
        minecart = Items.getRegisteredItem(StringPool2.aX);
        saddle = Items.getRegisteredItem(StringPool2.I);
        iron_door = Items.getRegisteredItem(StringPool2.bn);
        redstone = Items.getRegisteredItem(StringPool2.ch);
        snowball = Items.getRegisteredItem(StringPool2.a7);
        boat = Items.getRegisteredItem(StringPool2.ai);
        leather = Items.getRegisteredItem(StringPool2.R);
        milk_bucket = Items.getRegisteredItem(StringPool2.aA);
        brick = Items.getRegisteredItem(StringPool2.S);
        clay_ball = Items.getRegisteredItem(StringPool2.bP);
        reeds = Items.getRegisteredItem(StringPool2.bk);
        paper = Items.getRegisteredItem(StringPool2.bu);
        book = Items.getRegisteredItem(StringPool2.cd);
        slime_ball = Items.getRegisteredItem(StringPool2.aG);
        chest_minecart = Items.getRegisteredItem(StringPool2.ak);
        furnace_minecart = Items.getRegisteredItem(StringPool2.bW);
        egg = Items.getRegisteredItem(StringPool2.bc);
        compass = Items.getRegisteredItem(StringPool2.bU);
        fishing_rod = (ItemFishingRod)Items.getRegisteredItem(StringPool2.D);
        clock = Items.getRegisteredItem(StringPool2.cj);
        glowstone_dust = Items.getRegisteredItem(StringPool2.a4);
        fish = Items.getRegisteredItem(StringPool2.bI);
        cooked_fish = Items.getRegisteredItem(StringPool2.aj);
        dye = Items.getRegisteredItem(StringPool2.ar);
        bone = Items.getRegisteredItem(StringPool2.aH);
        sugar = Items.getRegisteredItem(StringPool2.bv);
        cake = Items.getRegisteredItem(StringPool2.cb);
        bed = Items.getRegisteredItem(StringPool2.aw);
        repeater = Items.getRegisteredItem(StringPool2.bt);
        cookie = Items.getRegisteredItem(StringPool2.u);
        filled_map = (ItemMap)Items.getRegisteredItem(StringPool2.X);
        shears = (ItemShears)Items.getRegisteredItem(StringPool2.bD);
        melon = Items.getRegisteredItem(StringPool2.bl);
        pumpkin_seeds = Items.getRegisteredItem(StringPool2.be);
        melon_seeds = Items.getRegisteredItem(StringPool2.ao);
        beef = Items.getRegisteredItem(StringPool2.p);
        cooked_beef = Items.getRegisteredItem(StringPool2.ag);
        chicken = Items.getRegisteredItem(StringPool2.b2);
        cooked_chicken = Items.getRegisteredItem(StringPool2.ci);
        mutton = Items.getRegisteredItem(StringPool2.a3);
        cooked_mutton = Items.getRegisteredItem(StringPool2.bK);
        rabbit = Items.getRegisteredItem(StringPool2.bR);
        cooked_rabbit = Items.getRegisteredItem(StringPool2.bo);
        rabbit_stew = Items.getRegisteredItem(StringPool2.as);
        rabbit_foot = Items.getRegisteredItem(StringPool2.m);
        rabbit_hide = Items.getRegisteredItem(StringPool2.b4);
        rotten_flesh = Items.getRegisteredItem(StringPool2.aW);
        ender_pearl = Items.getRegisteredItem(StringPool2.n);
        blaze_rod = Items.getRegisteredItem(StringPool2.b_);
        ghast_tear = Items.getRegisteredItem(StringPool2.Q);
        gold_nugget = Items.getRegisteredItem(StringPool2.aI);
        nether_wart = Items.getRegisteredItem(StringPool2.bb);
        potionitem = (ItemPotion)Items.getRegisteredItem(StringPool2.bf);
        glass_bottle = Items.getRegisteredItem(StringPool2.Z);
        spider_eye = Items.getRegisteredItem(StringPool2.N);
        fermented_spider_eye = Items.getRegisteredItem(StringPool2.b);
        blaze_powder = Items.getRegisteredItem(StringPool2.a_);
        magma_cream = Items.getRegisteredItem(StringPool2.j);
        brewing_stand = Items.getRegisteredItem(StringPool2.aB);
        cauldron = Items.getRegisteredItem(StringPool2.bj);
        ender_eye = Items.getRegisteredItem(StringPool2.U);
        speckled_melon = Items.getRegisteredItem(StringPool2.q);
        spawn_egg = Items.getRegisteredItem(StringPool2.ah);
        experience_bottle = Items.getRegisteredItem(StringPool2.am);
        fire_charge = Items.getRegisteredItem(StringPool2.b8);
        writable_book = Items.getRegisteredItem(StringPool2.bx);
        written_book = Items.getRegisteredItem(StringPool2.a1);
        emerald = Items.getRegisteredItem(StringPool2.bd);
        item_frame = Items.getRegisteredItem(StringPool2.bg);
        flower_pot = Items.getRegisteredItem(StringPool2.bC);
        carrot = Items.getRegisteredItem(StringPool2.af);
        potato = Items.getRegisteredItem(StringPool2.b5);
        baked_potato = Items.getRegisteredItem(StringPool2.at);
        poisonous_potato = Items.getRegisteredItem(StringPool2.ax);
        map = (ItemEmptyMap)Items.getRegisteredItem(StringPool2.b9);
        golden_carrot = Items.getRegisteredItem(StringPool2.aM);
        skull = Items.getRegisteredItem(StringPool2.H);
        carrot_on_a_stick = Items.getRegisteredItem(StringPool2.bZ);
        nether_star = Items.getRegisteredItem(StringPool2.al);
        pumpkin_pie = Items.getRegisteredItem(StringPool2.aZ);
        fireworks = Items.getRegisteredItem(StringPool2.E);
        firework_charge = Items.getRegisteredItem(StringPool2.bO);
        enchanted_book = (ItemEnchantedBook)Items.getRegisteredItem(StringPool2.c);
        comparator = Items.getRegisteredItem(StringPool2.f);
        netherbrick = Items.getRegisteredItem(StringPool2.ce);
        quartz = Items.getRegisteredItem(StringPool2.bS);
        tnt_minecart = Items.getRegisteredItem(StringPool2.bH);
        hopper_minecart = Items.getRegisteredItem(StringPool2.a9);
        armor_stand = (ItemArmorStand)Items.getRegisteredItem(StringPool2.ac);
        iron_horse_armor = Items.getRegisteredItem(StringPool2.F);
        golden_horse_armor = Items.getRegisteredItem(StringPool2.bQ);
        diamond_horse_armor = Items.getRegisteredItem(StringPool2.bw);
        lead = Items.getRegisteredItem(StringPool2.B);
        name_tag = Items.getRegisteredItem(StringPool2.r);
        command_block_minecart = Items.getRegisteredItem(StringPool2.aU);
        record_13 = Items.getRegisteredItem(StringPool2.z);
        record_cat = Items.getRegisteredItem(StringPool2.b1);
        record_blocks = Items.getRegisteredItem(StringPool2.aL);
        record_chirp = Items.getRegisteredItem(StringPool2.bY);
        record_far = Items.getRegisteredItem(StringPool2.a0);
        record_mall = Items.getRegisteredItem(StringPool2.M);
        record_mellohi = Items.getRegisteredItem(StringPool2.e);
        record_stal = Items.getRegisteredItem(StringPool2.aS);
        record_strad = Items.getRegisteredItem(StringPool2.av);
        record_ward = Items.getRegisteredItem(StringPool2.bX);
        record_11 = Items.getRegisteredItem(StringPool2.y);
        record_wait = Items.getRegisteredItem(StringPool2.aO);
        prismarine_shard = Items.getRegisteredItem(StringPool2.x);
        prismarine_crystals = Items.getRegisteredItem(StringPool2.aQ);
        banner = Items.getRegisteredItem(StringPool2.k);
    }
}

